# Project Euler
# Problem 12
# Solution by Ewen Bramble

# How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

terms = set()
for a in range(2,101):
    for b in range(2,101):
        terms.add(a**b)

print("Number of distinct terms: {}".format(len(terms)))